from collections.abc import Iterator, Mapping, Set

class NodeView(Mapping, Set):
    def __getitem__(self, key: str, /) -> dict: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
